### ISSUE TITLE
Bad Gateway for WaterData() URL

### ISSUE THREAD

**Issue by sjordan29** [cheginit/pynhd#25] opened 2021-08-19 13:56 UTC
Thanks for this library! I am on a Windows 10 and Python 3.8.10

I was running through the example contained in the phynhd readme file for USGS station ID 01482100. I get an error when I run:

`wd_cat = WaterData("catchmentsp")`

`catchments = wd_cat.byid("featureid", comids)`

It seems like the URL provided by `WaterData()` is dead. Do you know if this is a temporary problem, or a permanent change? I get the following error:

`---------------------------------------------------------------------------
ClientResponseError                       Traceback (most recent call last)
~\Anaconda3\envs\pangeo\lib\site-packages\async_retriever\async_retriever.py in _retrieve(uid, url, session, read_type, s_kwds, r_kwds)
     59         try:
---> 60             response.raise_for_status()
     61             resp = await getattr(response, read_type)(**r_kwds)

~\Anaconda3\envs\pangeo\lib\site-packages\aiohttp\client_reqrep.py in raise_for_status(self)
    999             self.release()
-> 1000             raise ClientResponseError(
   1001                 self.request_info,

ClientResponseError: 502, message='Bad Gateway', url=URL('https://labs.waterdata.usgs.gov/geoserver/wmadata/ows')

The above exception was the direct cause of the following exception:

ServiceError                              Traceback (most recent call last)
<ipython-input-20-3cd3edfbad6b> in <module>
----> 1 catchments = wd_cat.byid("featureid", comids)

~\Anaconda3\envs\pangeo\lib\site-packages\pynhd\pynhd.py in byid(self, featurename, featureids)
    233     def byid(self, featurename: str, featureids: Union[List[str], str]) -> gpd.GeoDataFrame:
    234         """Get features based on IDs."""
--> 235         resp = self.wfs.getfeature_byid(featurename, featureids)
    236         return self._to_geodf(resp)
    237 

~\Anaconda3\envs\pangeo\lib\site-packages\pygeoogc\pygeoogc.py in getfeature_byid(self, featurename, featureids)
    502 
    503         if len(featureids) > 200:
--> 504             return self.getfeature_byfilter(f"{featurename} IN ({fid_list})", method="POST")
    505 
    506         return self.getfeature_byfilter(f"{featurename} IN ({fid_list})")

~\Anaconda3\envs\pangeo\lib\site-packages\pygeoogc\pygeoogc.py in getfeature_byfilter(self, cql_filter, method)
    550         elif method == "POST":
    551             headers = {"content-type": "application/x-www-form-urlencoded"}
--> 552             resp = ar.retrieve(
    553                 [self.url], self.read_method, [{"data": payload, "headers": headers}], "POST"
    554             )

~\Anaconda3\envs\pangeo\lib\site-packages\async_retriever\async_retriever.py in retrieve(urls, read, request_kwds, request_method, max_workers, cache_name, family)
    190     )
    191 
--> 192     return [r for _, r in sorted(tlz.concat(results))]
    193 
    194 

~\Anaconda3\envs\pangeo\lib\site-packages\async_retriever\async_retriever.py in <genexpr>(.0)
    184     chunked_reqs = tlz.partition_all(max_workers, inp.url_kwds)
    185     results = (
--> 186         loop.run_until_complete(
    187             async_session(c, inp.read, inp.r_kwds, inp.request_method, inp.cache_name, inp.family),
    188         )

~\Anaconda3\envs\pangeo\lib\site-packages\nest_asyncio.py in run_until_complete(self, future)
     68                 raise RuntimeError(
     69                     'Event loop stopped before Future completed.')
---> 70             return f.result()
     71 
     72     def _run_once(self):

~\Anaconda3\envs\pangeo\lib\asyncio\futures.py in result(self)
    176         self.__log_traceback = False
    177         if self._exception is not None:
--> 178             raise self._exception
    179         return self._result
    180 

~\Anaconda3\envs\pangeo\lib\asyncio\tasks.py in __step(***failed resolving arguments***)
    278                 # We use the `send` method directly, because coroutines
    279                 # don't have `__iter__` and `__next__` methods.
--> 280                 result = coro.send(None)
    281             else:
    282                 result = coro.throw(exc)

~\Anaconda3\envs\pangeo\lib\site-packages\async_retriever\async_retriever.py in async_session(url_kwds, read, r_kwds, request_method, cache_name, family)
    115         request_func = getattr(session, request_method.lower())
    116         tasks = (_retrieve(uid, u, request_func, read, kwds, r_kwds) for uid, u, kwds in url_kwds)
--> 117         return await asyncio.gather(*tasks)
    118 
    119 

~\Anaconda3\envs\pangeo\lib\asyncio\tasks.py in __wakeup(self, future)
    347     def __wakeup(self, future):
    348         try:
--> 349             future.result()
    350         except BaseException as exc:
    351             # This may also be a cancellation.

~\Anaconda3\envs\pangeo\lib\asyncio\tasks.py in __step(***failed resolving arguments***)
    278                 # We use the `send` method directly, because coroutines
    279                 # don't have `__iter__` and `__next__` methods.
--> 280                 result = coro.send(None)
    281             else:
    282                 result = coro.throw(exc)

~\Anaconda3\envs\pangeo\lib\site-packages\async_retriever\async_retriever.py in _retrieve(uid, url, session, read_type, s_kwds, r_kwds)
     61             resp = await getattr(response, read_type)(**r_kwds)
     62         except (ClientResponseError, ContentTypeError) as ex:
---> 63             raise ServiceError(await response.text()) from ex
     64         else:
     65             return uid, resp

ServiceError: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>`

**Comment by cheginit** [comment] 2021-08-19 16:08
Thank you!

500 errors usually mean that the service is temporary unavailable. I just gave it try, and it works now.

**Comment by sjordan29** [comment] 2021-08-20 13:45
Okay, that is good to know. I am still getting that error, but I'll keep trying. Thanks for your help!

**Comment by sjordan29** [comment] 2021-08-20 20:59
Hi! I figured out the problem -- I was trying to get too many comids at once (12700). After a little testing, it seems like the max is 3000. 

I was able to get all the info like this:

```python 
ls = []
for i in range(1, int(len(comids) / 1000.)+2):
    mn_val = (i-1) * 1000 
    if i * 1000 > len(comids):
        mx_val = len(comids)
    else:
        mx_val = i * 1000
    vals = comids[mn_val:mx_val]
    print(mn_val, mx_val)
    cat = wd_cat.byid("featureid", vals)
    # df.append(cat, ignore_index=True)
    ls.append(cat)
```

**Comment by cheginit** [comment] 2021-08-21 09:49
Thanks, for following up on this, and finding the issue.

I didn't notice that you're working with a different station ID than the one in the README. So I now am able to reproduce this error. Please provide a minimal working example (MWE) next time, so I can reproduce the error. This is a MWE that reproduces your error.

```python
from pynhd import NLDI, WaterData
nldi = NLDI()
station_id = "01482100"

basin = nldi.get_basins(station_id)
flw_trib = nldi.navigate_byid(
    fsource="nwissite",
    fid=f"USGS-{station_id}",
    navigation="upstreamTributaries",
    source="flowlines",
    distance=1000,
)
comids = flw_trib.nhdplus_comid.to_list()
wd = WaterData("catchmentsp")
catchments = wd.byid("featureid", comids)
```

Since you mentioned that there's a limit, I am going to work on a fix. I will ping you once it's done so just to make sure it's fixed.

**Comment by cheginit** [comment] 2021-08-21 10:52
I pushed a fix to `pygeoogc` which is the package `pynhd` uses for sending requests. Can you please install it from git and retry using the MWE that I provided?

You can install the fix like so:

```bash
pip install git+https://github.com/cheginit/pygeoogc
```

**Comment by sjordan29** [comment] 2021-08-24 14:16
That worked! Thanks so much.

**Comment by cheginit** [comment] 2021-08-24 14:29
Great! I am going to release a new version with the fix. Thanks for reporting and testing.

**Closed by cheginit** 2021-08-24 14:29 UTC
Labels: bug
